### ISSUE TITLE
when using the modul I get "Error: Command "dataset" is not available outside of a Sanity project context."

### ISSUE THREAD

**Issue by devopsweep** [sanity-io/github-action-sanity#10]
Hi,
when I use the workflow you published:

```
jobs:
  backup-dataset:
    runs-on: ubuntu-18.04
    name: Backup dataset
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.3
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: . dataset export production backups/backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
```

I get this error on each:
`Error: Command "dataset" is not available outside of a Sanity project context.
`
