### ISSUE TITLE
Error: No files were found with the provided path

### ISSUE THREAD

**Issue by bzmillerboy** [sanity-io/github-action-sanity#12]
I'm getting the following error when my action run.

`Error: No files were found with the provided path: backups/backup.tar.gz. No artifacts will be uploaded.`

**Version**: v0.4

Here is my .yml action code (note: I have a monorepo and 'studio' is the folder where Sanity resides):

```
name: Sanity Dataset Backup
on:
  schedule:
    # Runs at 06:00pm EST everyday
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Backup dataset
    defaults:
      run:
        working-directory: studio
    steps:
      - uses: actions/checkout@v2
      - name: Export dataset
        uses: sanity-io/github-action-sanity@v0.4
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: studio dataset export production backups/backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          # Fails the workflow if no files are found; defaults to 'warn'
          if-no-files-found: error
```
<img width="1558" alt="Screenshot 2023-02-08 at 1 52 50 PM" src="https://user-images.githubusercontent.com/1130899/217624937-9244b4cc-d499-4061-8a0b-fad1a87785cc.png">
