### ISSUE TITLE
Github deprecated Ubuntu 18.04

### ISSUE THREAD

**Issue by simovic94** [sanity-io/github-action-sanity#13]
I use this package v0.4 and an example from this github repo to make a backup on github. After GitHub deprecated Ubuntu 18.04 my action didn't work. I tried to change Ubuntu on 22 and try to change every package into github action but doesn't work. Does anyone have a similar problem or solution for this problem?

**Comment by carlosganzerla** [comment]
@simovic94 I just ported the shell code from the repo and worked for me:
```yml
name: deploy
on:
  release:
    types: [published]

jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: npm install -g @sanity/cli &&
          sanity install && 
          SANITY_AUTH_TOKEN=$SANITY_AUTH_TOKEN &&
          sanity deploy
```
