### ISSUE TITLE
SCRIPT must be provided. `sanity exec <script>`

### ISSUE THREAD

**Issue by thunder87** [sanity-io/github-action-sanity#8]
Using v0.3 to execute sanity script results in **"Error: SCRIPT must be provided."**

```
name: Sanity Sync Jobs Routine
on:
  workflow_dispatch:
  # schedule:
  # Every hour between 7-19
  # - cron: '0 7-19 * * *'
jobs:
  sanity-exec:
    runs-on: ubuntu-latest
    name: Sync data
    steps:
      - uses: actions/checkout@v2
      - name: Sync data
        uses: sanity-io/github-action-sanity@v0.3
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        with:
          args: studio exec functions/syncJobs.js

```

Response
```
Error: SCRIPT must be provided. `sanity exec <script>`
    at execScript (/github/workspace/node_modules/@sanity/core/lib/actions/exec/execScript.js:41:[11](https://github.com/guilty-as/safe-bemanning/runs/8078208168?check_suite_focus=true#step:4:12))
    at Object.action (/github/workspace/node_modules/@sanity/util/lib/lazyRequire.js:14:10)
    at _.runCommand (/usr/local/share/.config/yarn/global/node_modules/@sanity/cli/bin/sanity-cli.js:3608:2242)

```

**Comment by geball** [comment]
Thanks @thunder87. We'll take a look.

**Comment by geball** [comment]
No matter what I passed to `sanity exec`, I couldn't avoid that same error.

I can look into this a bit more, but in the meantime I think you can run your Action successfully with:

```yml
name: Sanity Sync Jobs Routine
on:
  workflow_dispatch:
  # schedule:
  # Every hour between 7-19
  # - cron: '0 7-19 * * *'
jobs:
  sanity-exec:
    runs-on: ubuntu-latest
    name: Sync data
    steps:
      - uses: actions/checkout@v2
      - name: Sync data
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
        run: |
          yarn global add @sanity/cli
          cd sanity && sanity install
          sanity exec functions/syncJobs.js
```
